version: '3.8'

services:
  db:
    image: postgres:16
    container_name: postgres_db
    restart: always
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: futbol_base_tfg
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  ktor-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ktor_server
    depends_on:
      - db
    env_file: .env
    environment:
      PORT: ${PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DATABASE_URL: jdbc:postgresql://db:5432/futbol_base_tfg
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "8080:8080"
    restart: always

volumes:
  postgres_data:
